title: Olayinka Muizz
logo: image1.jpg
description: I am a highly qualified professional seeking opportunities as a Risk Analyst, Business Analyst, or Data Analyst. Proficient in statistical and data analytics tools such as E-view, Excel, SQL, and PowerBi. 
show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
